### ISSUE TITLE
Initial HTML set up

### ISSUE THREAD

**Issue by twalker7** [twalker7/HTeamL-Project#1]
## Requirements 
* Create the HTML page that needs :
    * header 
    * text area jumbotron for a drink recipe with a select list
    *  image jumbotron of artwork with a button above it
    * footer 
    

* Create Style Sheet for HTML page

* Add Functionality to button and select elements and add items to the select list

**Comment by Narmstrongv** [comment]
Complete.

**Comment by Narmstrongv** [comment]
Complete.
